version: 0.1

phases:
  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm install -g serverless
      - serverless -v -s $(echo ${CODEBUILD_INITIATOR} | cut -d'/' -f2 | cut -d'_' -f3) deploy --stage prod
